exports.data = {
	'raw_ferroconcrete' : 'Skała',
	'raw_sandstone' : 'Skała',
	'sandstone' : 'Kamień',
	'raw_packaging' : 'Drzewo',
	'raw_cypress' : 'Drzewo',
	'cypress' : 'Drewno',
	'raw_luxury_materials' : 'Marmur',
	'raw_alabaster' : 'Marmur',
	'alabaster' : 'Marmur',
	'raw_flavorants' : 'Kwiat',
	'raw_dye' : 'Kwiat',
	'dye' : 'Barwnik',
	'raw_convenience_food' : 'Winogrona',
	'raw_wine' : 'Winogrona',
	'wine' : 'Wino',
	'raw_filters' : 'Skała wapienna',
	'raw_limestone' : 'Skała wapienna',
	'limestone' : 'Wapień',
	'raw_renewable_resources' : 'Drzewo hebanowca',
	'raw_ebony' : 'Drzewo hebanowca',
	'ebony' : 'Heban',
	'raw_steel' : 'Ruda żelaza',
	'raw_lead' : 'Ruda żelaza',
	'lead' : 'Żelazo',
	'raw_dna_data' : 'Wełna',
	'raw_cloth' : 'Wełna',
	'cloth' : 'Tkanina',
	'raw_semiconductors' : 'Klejnot',
	'raw_gems' : 'Klejnot',
	'gems' : 'Biżuteria',
	'raw_electromagnets' : 'Ruda miedzi',
	'raw_bronze' : 'Ruda miedzi',
	'bronze' : 'Miedź',
	'raw_gas' : 'Skała granitowa',
	'raw_granite' : 'Skała granitowa',
	'granite' : 'Granit',
	'raw_plastics' : 'Nieprzetworzony alabaster',
	'raw_marble' : 'Nieprzetworzony alabaster',
	'marble' : 'Alabaster',
	'raw_robots' : 'Bryłka złota',
	'raw_gold' : 'Bryłka złota',
	'gold' : 'Złoto',
	'raw_bionics' : 'Plaster miodu',
	'raw_honey' : 'Plaster miodu',
	'honey' : 'Miód',
	'raw_nutrition_research' : 'Zioła',
	'raw_herbs' : 'Zioła',
	'herbs' : 'Suszone zioła',
	'raw_smart_materials' : 'Glina',
	'raw_brick' : 'Glina',
	'brick' : 'Cegła',
	'raw_papercrete' : 'Juta',
	'raw_ropes' : 'Juta',
	'ropes' : 'Lina',
	'raw_preservatives' : 'Nieoczyszczona sól',
	'raw_salt' : 'Nieoczyszczona sól',
	'salt' : 'Sól',
	'raw_translucent_concrete' : 'Kwarc',
	'raw_glass' : 'Kwarc',
	'glass' : 'Szkło',
	'raw_superconductors' : 'Steatyt',
	'raw_talc' : 'Steatyt',
	'talc' : 'Proszek talkowy',
	'raw_purified_water' : 'Skała bazaltowa',
	'raw_basalt' : 'Skała bazaltowa',
	'basalt' : 'Bazalt',
	'raw_nanoparticles' : 'Ruda cynku',
	'raw_brass' : 'Ruda cynku',
	'brass' : 'Mosiądz',
	'raw_biogeochemical_data' : 'Bloki siarkowe',
	'raw_gunpowder' : 'Bloki siarkowe',
	'gunpowder' : 'Proch strzelniczy',
	'raw_algae' : 'Kokony',
	'raw_silk' : 'Kokony',
	'silk' : 'Jedwab',
	'raw_paper_batteries' : 'Świerczyna',
	'raw_paper' : 'Świerczyna',
	'paper' : 'Papier',
	'raw_transester_gas' : 'Ziarna kawy',
	'raw_coffee' : 'Ziarna kawy',
	'coffee' : 'Kawa',
	'raw_nanowire' : 'Ruda niklu',
	'raw_wire' : 'Ruda niklu',
	'wire' : 'Drut',
	'raw_ai_data' : 'Kaolin',
	'raw_porcelain' : 'Kaolin',
	'porcelain' : 'Porcelana',
	'raw_bioplastics' : 'Drewno sosnowe',
	'raw_tar' : 'Drewno sosnowe',
	'tar' : 'Smoła',
	'raw_coke' : 'Węgiel',
	'coke' : 'Koks',
	'raw_rubber' : 'Lateks',
	'rubber' : 'Guma',
	'raw_textiles' : 'Bawełna',
	'textiles' : 'Przędza',
	'raw_whaleoil' : 'Wieloryby',
	'whaleoil' : 'Tran',
	'raw_fertilizer' : 'Guano',
	'fertilizer' : 'Nawóz',
	'raw_asbestos' : 'Nieprzetworzony azbest',
	'asbestos' : 'Azbest',
	'raw_petroleum' : 'Ropa naftowa',
	'petroleum' : 'Benzyna',
	'raw_machineparts' : 'Ruda wolframu',
	'machineparts' : 'Części maszynowe',
	'raw_tinplate' : 'Ruda cyny',
	'tinplate' : 'Blacha ocynowana',
	'raw_explosives' : 'Ziemia okrzemkowa',
	'explosives' : 'Materiały wybuchowe',
	'ferroconcrete' : 'ME|Żelbet',
	'convenience_food' : 'ME|Przetworzona żywność',
	'flavorants' : 'ME|Aromaty',
	'packaging' : 'ME|Opakowania',
	'luxury_materials' : 'ME|Towary luksusowe',
	'renewable_resources' : 'PME|Zasoby odnawialne',
	'steel' : 'Stal',
	'semiconductors' : 'Półprzewodniki',
	'filters' : 'Filtry przemysłowe',
	'dna_data' : 'Materiał genetyczny',
	'electromagnets' : 'CE|Elektromagnesy',
	'gas' : 'CE|Gaz',
	'plastics' : 'CE|Plastik',
	'robots' : 'CE|Roboty',
	'bionics' : 'CE|Dane bioniczne',
	'translucent_concrete' : 'TMR|Transparentny beton',
	'smart_materials' : 'TMR|Tworzywa inteligentne',
	'papercrete' : 'TMR|Beton papierowy',
	'preservatives' : 'Konserwanty',
	'nutrition_research' : 'TMR|Żywność dietetyczna',
	'biogeochemical_data' : 'FUT|Dane biogeochemiczne',
	'purified_water' : 'FUT|Woda ultraczysta',
	'algae' : 'FUT|Algi',
	'superconductors' : 'Nadprzewodniki',
	'nanoparticles' : 'FUT|Nanocząsteczki',
	'nanowire' : 'Nanokabel',
	'transester_gas' : 'Gaz transestryfikowany',
	'ai_data' : 'Dane SI',
	'paper_batteries' : 'Baterie papierowe',
	'bioplastics' : 'Bioplastiki',
	'promethium' : 'Promet'
};
